### ISSUE TITLE
Trying to allocate > 1gb of memory 😒

### ISSUE THREAD

**Issue by dannyrandall** [byuoitav/event-router-microservice#50]
log statements from the router when it crashes: 
```
2017/07/13 16:17:29 Not all of the message was recieved
runtime: out of memory: cannot allocate 1110900736-byte block (4194304 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x37bd34, 0xd)
	/usr/local/go/src/runtime/panic.go:596 +0x70
runtime.largeAlloc(0x42363031, 0x10800f01, 0x4)
	/usr/local/go/src/runtime/malloc.go:797 +0xe0
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:690 +0x30
runtime.systemstack(0x10818000)
	/usr/local/go/src/runtime/asm_arm.s:264 +0x80
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1132

goroutine 61 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_arm.s:209 +0x4 fp=0x109c1eb8 sp=0x109c1eb4
runtime.mallocgc(0x42363031, 0x327e28, 0x1, 0x1c)
	/usr/local/go/src/runtime/malloc.go:691 +0x9e0 fp=0x109c1f14 sp=0x109c1eb8
runtime.makeslice(0x327e28, 0x42363031, 0x42363031, 0x1c, 0x1c, 0x0)
	/usr/local/go/src/runtime/slice.go:54 +0x68 fp=0x109c1f38 sp=0x109c1f14
github.com/xuther/go-message-router/subscriber.(*readSubscription).StartListener.func1(0x10abc2e0)
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/subscriber/subscriber.go:148 +0x230 fp=0x109c1fe4 sp=0x109c1f38
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:1017 +0x4 fp=0x109c1fe4 sp=0x109c1fe4
created by github.com/xuther/go-message-router/subscriber.(*readSubscription).StartListener
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/subscriber/subscriber.go:176 +0x2c

goroutine 1 [IO wait]:
net.runtime_pollWait(0x76eb7f00, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x44
net.(*pollDesc).wait(0x1091ec3c, 0x72, 0x0, 0x10988650)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x28
net.(*pollDesc).waitRead(0x1091ec3c, 0xffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x24
net.(*netFD).accept(0x1091ec00, 0x0, 0x5112f8, 0x10988650)
	/usr/local/go/src/net/fd_unix.go:430 +0x15c
net.(*TCPListener).accept(0x1080cbb8, 0x1ddbc8, 0x12cc8, 0x112a0)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x20
net.(*TCPListener).AcceptTCP(0x1080cbb8, 0x32ca80, 0x41b44, 0x41b88)
	/usr/local/go/src/net/tcpsock.go:215 +0x3c
github.com/labstack/echo.tcpKeepAliveListener.Accept(0x1080cbb8, 0x650ac, 0x10931d0c, 0x10931d10, 0x10931d08)
	/home/ubuntu/.go_project/src/github.com/labstack/echo/echo.go:713 +0x1c
github.com/labstack/echo.(*tcpKeepAliveListener).Accept(0x1080cbc0, 0x390338, 0x109908a0, 0x513b00, 0x108ff680)
	<autogenerated>:104 +0x4c
net/http.(*Server).Serve(0x10872600, 0x513438, 0x1080cbc0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2643 +0x1ac
github.com/labstack/echo.(*Echo).StartServer(0x1086c380, 0x10872600, 0x10931e00, 0x2e1e74)
	/home/ubuntu/.go_project/src/github.com/labstack/echo/echo.go:646 +0x318
github.com/labstack/echo.(*Echo).Start(0x1086c380, 0x37863f, 0x5, 0x3, 0x3)
	/home/ubuntu/.go_project/src/github.com/labstack/echo/echo.go:587 +0x48
main.main()
	/home/ubuntu/.go_project/src/github.com/byuoitav/event-router-microservice/server.go:122 +0x710

goroutine 5 [IO wait]:
net.runtime_pollWait(0x76eb7f78, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x44
net.(*pollDesc).wait(0x1095a03c, 0x72, 0x0, 0x1091af10)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x28
net.(*pollDesc).waitRead(0x1095a03c, 0xffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x24
net.(*netFD).accept(0x1095a000, 0x0, 0x5112f8, 0x1091af10)
	/usr/local/go/src/net/fd_unix.go:430 +0x15c
net.(*TCPListener).accept(0x10958008, 0x2c70a0, 0x31bca0, 0x1091e400)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x20
net.(*TCPListener).AcceptTCP(0x10958008, 0x1091e400, 0x1081ffb0, 0x1091f700)
	/usr/local/go/src/net/tcpsock.go:215 +0x3c
github.com/xuther/go-message-router/publisher.(*publisher).Listen(0x10814930, 0x0, 0x0)
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/publisher/message-publisher.go:74 +0x2b4
created by github.com/xuther/go-message-router/router.(*Router).publisher
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/router/router.go:50 +0x1a8

goroutine 17 [select]:
github.com/xuther/go-message-router/publisher.(*publisher).runMembership.func1(0x10814930)
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/publisher/message-publisher.go:126 +0x3c4
created by github.com/xuther/go-message-router/publisher.(*publisher).runMembership
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/publisher/message-publisher.go:154 +0x2c

goroutine 18 [chan receive]:
github.com/xuther/go-message-router/publisher.(*publisher).runBroadcaster.func1(0x10814930)
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/publisher/message-publisher.go:102 +0x70
created by github.com/xuther/go-message-router/publisher.(*publisher).runBroadcaster
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/publisher/message-publisher.go:118 +0x2c

goroutine 6 [select]:
github.com/xuther/go-message-router/router.(*Router).publisher.func1(0x53af48, 0x513458, 0x10814930, 0x1091a7d0)
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/router/router.go:55 +0xfc
created by github.com/xuther/go-message-router/router.(*Router).publisher
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/router/router.go:63 +0x204

goroutine 7 [select]:
github.com/xuther/go-message-router/router.(*Router).router.func1(0x53af48, 0x108ff100, 0x1091a830)
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/router/router.go:230 +0x3a8
created by github.com/xuther/go-message-router/router.(*Router).router
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/router/router.go:259 +0x3a8

goroutine 8 [select]:
github.com/xuther/go-message-router/subscriber.(*subscriber).startSubscriptionManager.func1(0x108ff440)
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/subscriber/subscriber.go:108 +0x2bc
created by github.com/xuther/go-message-router/subscriber.(*subscriber).startSubscriptionManager
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/subscriber/subscriber.go:123 +0x54

goroutine 9 [chan receive]:
github.com/xuther/go-message-router/router.(*Router).reciever.func1(0x1091a940, 0x53af48, 0x513c40, 0x108ff440, 0x1080cb18)
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/router/router.go:80 +0xa4
created by github.com/xuther/go-message-router/router.(*Router).reciever
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/router/router.go:124 +0x148

goroutine 10 [runnable]:
github.com/xuther/go-message-router/subscriber.(*subscriber).Read(0x108ff440, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/subscriber/subscriber.go:54 +0x44
github.com/xuther/go-message-router/router.(*Router).reciever.func2(0x53af48, 0x513c40, 0x108ff440, 0x1091a950)
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/router/router.go:131 +0x24
created by github.com/xuther/go-message-router/router.(*Router).reciever
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/router/router.go:142 +0x1a4

goroutine 52 [IO wait]:
net.runtime_pollWait(0x76eb7c30, 0x72, 0x10bae720)
	/usr/local/go/src/runtime/netpoll.go:164 +0x44
net.(*pollDesc).wait(0x1095a97c, 0x72, 0x511bf8, 0x5100e8)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x28
net.(*pollDesc).waitRead(0x1095a97c, 0x10bae720, 0x1c)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x24
net.(*netFD).Read(0x1095a940, 0x10bae720, 0x1c, 0x1c, 0x0, 0x511bf8, 0x5100e8)
	/usr/local/go/src/net/fd_unix.go:250 +0x148
net.(*conn).Read(0x109580f8, 0x10bae720, 0x1c, 0x1c, 0x1c, 0x1c, 0x0)
	/usr/local/go/src/net/net.go:181 +0x58
github.com/xuther/go-message-router/subscriber.(*readSubscription).StartListener.func1(0x10956700)
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/subscriber/subscriber.go:132 +0x8c
created by github.com/xuther/go-message-router/subscriber.(*readSubscription).StartListener
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/subscriber/subscriber.go:176 +0x2c

goroutine 12 [IO wait]:
net.runtime_pollWait(0x76eb7e88, 0x72, 0x1087f000)
	/usr/local/go/src/runtime/netpoll.go:164 +0x44
net.(*pollDesc).wait(0x1091ed3c, 0x72, 0x511bf8, 0x5100e8)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x28
net.(*pollDesc).waitRead(0x1091ed3c, 0x1087f000, 0x1000)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x24
net.(*netFD).Read(0x1091ed00, 0x1087f000, 0x1000, 0x1000, 0x0, 0x511bf8, 0x5100e8)
	/usr/local/go/src/net/fd_unix.go:250 +0x148
net.(*conn).Read(0x1080cbe0, 0x1087f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x58
net/http.(*connReader).Read(0x10814d80, 0x1087f000, 0x1000, 0x1000, 0x1d6dd0, 0x1091ed00, 0x0)
	/usr/local/go/src/net/http/server.go:754 +0x168
bufio.(*Reader).fill(0x10814db0)
	/usr/local/go/src/bufio/bufio.go:97 +0xf4
bufio.(*Reader).Peek(0x10814db0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x58
net/http.(*conn).readRequest(0x1080f860, 0x513a88, 0x108ff700, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:931 +0xc98
net/http.(*conn).serve(0x1080f860, 0x513a88, 0x108ff700)
	/usr/local/go/src/net/http/server.go:1763 +0x3b4
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x234

goroutine 53 [IO wait]:
net.runtime_pollWait(0x76eb7bb8, 0x72, 0x109b4780)
	/usr/local/go/src/runtime/netpoll.go:164 +0x44
net.(*pollDesc).wait(0x1095aefc, 0x72, 0x511bf8, 0x5100e8)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x28
net.(*pollDesc).waitRead(0x1095aefc, 0x109b4780, 0x1c)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x24
net.(*netFD).Read(0x1095aec0, 0x109b4780, 0x1c, 0x1c, 0x0, 0x511bf8, 0x5100e8)
	/usr/local/go/src/net/fd_unix.go:250 +0x148
net.(*conn).Read(0x109b80f0, 0x109b4780, 0x1c, 0x1c, 0x1c, 0x1c, 0x1)
	/usr/local/go/src/net/net.go:181 +0x58
github.com/xuther/go-message-router/subscriber.(*readSubscription).StartListener.func1(0x109b4740)
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/subscriber/subscriber.go:132 +0x8c
created by github.com/xuther/go-message-router/subscriber.(*readSubscription).StartListener
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/subscriber/subscriber.go:176 +0x2c

goroutine 54 [IO wait]:
net.runtime_pollWait(0x76eb7b40, 0x72, 0x109f5000)
	/usr/local/go/src/runtime/netpoll.go:164 +0x44
net.(*pollDesc).wait(0x109b6cbc, 0x72, 0x511bf8, 0x5100e8)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x28
net.(*pollDesc).waitRead(0x109b6cbc, 0x109f5000, 0x1000)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x24
net.(*netFD).Read(0x109b6c80, 0x109f5000, 0x1000, 0x1000, 0x0, 0x511bf8, 0x5100e8)
	/usr/local/go/src/net/fd_unix.go:250 +0x148
net.(*conn).Read(0x109b8100, 0x109f5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x58
net/http.(*connReader).Read(0x10815290, 0x109f5000, 0x1000, 0x1000, 0x1d6dd0, 0x109b6c80, 0x0)
	/usr/local/go/src/net/http/server.go:754 +0x168
bufio.(*Reader).fill(0x108152c0)
	/usr/local/go/src/bufio/bufio.go:97 +0xf4
bufio.(*Reader).Peek(0x108152c0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x58
net/http.(*conn).readRequest(0x109c8840, 0x513a88, 0x10a1e060, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:931 +0xc98
net/http.(*conn).serve(0x109c8840, 0x513a88, 0x10a1e060)
	/usr/local/go/src/net/http/server.go:1763 +0x3b4
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x234

goroutine 68 [chan receive]:
github.com/xuther/go-message-router/publisher.(*subscription).StartWriter.func1(0x1091af00)
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/publisher/message-publisher.go:162 +0x54
created by github.com/xuther/go-message-router/publisher.(*subscription).StartWriter
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/publisher/message-publisher.go:190 +0x2c

goroutine 19 [IO wait]:
net.runtime_pollWait(0x76eb7d98, 0x72, 0x10ba4220)
	/usr/local/go/src/runtime/netpoll.go:164 +0x44
net.(*pollDesc).wait(0x109b653c, 0x72, 0x511bf8, 0x5100e8)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x28
net.(*pollDesc).waitRead(0x109b653c, 0x10ba4220, 0x1c)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x24
net.(*netFD).Read(0x109b6500, 0x10ba4220, 0x1c, 0x1c, 0x0, 0x511bf8, 0x5100e8)
	/usr/local/go/src/net/fd_unix.go:250 +0x148
net.(*conn).Read(0x10958010, 0x10ba4220, 0x1c, 0x1c, 0x1c, 0x1c, 0x0)
	/usr/local/go/src/net/net.go:181 +0x58
github.com/xuther/go-message-router/subscriber.(*readSubscription).StartListener.func1(0x10956140)
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/subscriber/subscriber.go:132 +0x8c
created by github.com/xuther/go-message-router/subscriber.(*readSubscription).StartListener
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/subscriber/subscriber.go:176 +0x2c

goroutine 15 [IO wait]:
net.runtime_pollWait(0x76eb7d20, 0x72, 0x109a1000)
	/usr/local/go/src/runtime/netpoll.go:164 +0x44
net.(*pollDesc).wait(0x1091f0bc, 0x72, 0x511bf8, 0x5100e8)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x28
net.(*pollDesc).waitRead(0x1091f0bc, 0x109a1000, 0x1000)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x24
net.(*netFD).Read(0x1091f080, 0x109a1000, 0x1000, 0x1000, 0x0, 0x511bf8, 0x5100e8)
	/usr/local/go/src/net/fd_unix.go:250 +0x148
net.(*conn).Read(0x1080cc98, 0x109a1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x58
net/http.(*connReader).Read(0x10814f30, 0x109a1000, 0x1000, 0x1000, 0x1d6dd0, 0x1091f080, 0x0)
	/usr/local/go/src/net/http/server.go:754 +0x168
bufio.(*Reader).fill(0x10814f60)
	/usr/local/go/src/bufio/bufio.go:97 +0xf4
bufio.(*Reader).Peek(0x10814f60, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x58
net/http.(*conn).readRequest(0x1080f980, 0x513a88, 0x108ffb20, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:931 +0xc98
net/http.(*conn).serve(0x1080f980, 0x513a88, 0x108ffb20)
	/usr/local/go/src/net/http/server.go:1763 +0x3b4
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x234

goroutine 16 [IO wait]:
net.runtime_pollWait(0x76eb7ca8, 0x72, 0x109f3000)
	/usr/local/go/src/runtime/netpoll.go:164 +0x44
net.(*pollDesc).wait(0x1091f1bc, 0x72, 0x511bf8, 0x5100e8)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x28
net.(*pollDesc).waitRead(0x1091f1bc, 0x109f3000, 0x1000)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x24
net.(*netFD).Read(0x1091f180, 0x109f3000, 0x1000, 0x1000, 0x0, 0x511bf8, 0x5100e8)
	/usr/local/go/src/net/fd_unix.go:250 +0x148
net.(*conn).Read(0x1080cca8, 0x109f3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x58
net/http.(*connReader).Read(0x10814f90, 0x109f3000, 0x1000, 0x1000, 0x1d6dd0, 0x1091f180, 0x0)
	/usr/local/go/src/net/http/server.go:754 +0x168
bufio.(*Reader).fill(0x10814fc0)
	/usr/local/go/src/bufio/bufio.go:97 +0xf4
bufio.(*Reader).Peek(0x10814fc0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x58
net/http.(*conn).readRequest(0x1080f9e0, 0x513a88, 0x108ffc00, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:931 +0xc98
net/http.(*conn).serve(0x1080f9e0, 0x513a88, 0x108ffc00)
	/usr/local/go/src/net/http/server.go:1763 +0x3b4
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x234

goroutine 66 [chan receive]:
github.com/xuther/go-message-router/publisher.(*subscription).StartWriter.func1(0x1091ad70)
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/publisher/message-publisher.go:162 +0x54
created by github.com/xuther/go-message-router/publisher.(*subscription).StartWriter
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/publisher/message-publisher.go:190 +0x2c

goroutine 55 [IO wait]:
net.runtime_pollWait(0x76eb7a50, 0x72, 0x10bae140)
	/usr/local/go/src/runtime/netpoll.go:164 +0x44
net.(*pollDesc).wait(0x1095bb3c, 0x72, 0x511bf8, 0x5100e8)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x28
net.(*pollDesc).waitRead(0x1095bb3c, 0x10bae140, 0x1c)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x24
net.(*netFD).Read(0x1095bb00, 0x10bae140, 0x1c, 0x1c, 0x0, 0x511bf8, 0x5100e8)
	/usr/local/go/src/net/fd_unix.go:250 +0x148
net.(*conn).Read(0x109b8108, 0x10bae140, 0x1c, 0x1c, 0x1c, 0x1c, 0x0)
	/usr/local/go/src/net/net.go:181 +0x58
github.com/xuther/go-message-router/subscriber.(*readSubscription).StartListener.func1(0x109b48a0)
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/subscriber/subscriber.go:132 +0x8c
created by github.com/xuther/go-message-router/subscriber.(*readSubscription).StartListener
	/home/ubuntu/.go_project/src/github.com/xuther/go-message-router/subscriber/subscriber.go:176 +0x2c
```

**Comment by dannyrandall** [comment]
It doesn't seem related to the number of events that have been sent, or the time the router has been up.

**Comment by dannyrandall** [comment]
With some extra debugging code, the output from the go-message-router as it crashes is: 
```
2017/07/13 17:15:04 Not all of the message was recieved
2017/07/13 17:15:04 Message recieved from: ITB-1106B-CP2.byu.edu:7000
2017/07/13 17:15:04 Message length: 44/301
2017/07/13 17:15:04 First 10 bytes: {"hostname
runtime: out of memory: cannot allocate 1986985984-byte block (5242880 in use)
fatal error: out of memory

```
